'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, CheckCircle2, Compass, Mail, MapPin, Phone, ShieldCheck } from 'lucide-react'

export default function AboutPage() {
  return (
    <main className="about-page">
      <div className="utility"><div className="container utility-inner"><span>INTEGRATED ENGINEERING SERVICES</span><span className="utility-right"><MapPin size={13} /> Abuja, Nigeria <span className="utility-dot" /> <a href="mailto:Consultingmfy@gmail.com">Consultingmfy@gmail.com</a></span></div></div>
      <header className="site-header"><div className="container nav-inner"><Link className="brand" href="/"><img className="brand-logo" src="/mfy-logo-transparent.png" alt="MFY logo" /><span className="brand-name">MFY Consulting Ltd</span></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/capabilities">Capabilities</Link><Link href="/#approach">Approach</Link><Link href="/#sectors">Sectors</Link><Link href="/about">About MFY</Link><Link className="nav-cta" href="/#contact">Start a conversation <ArrowUpRight size={15} /></Link></nav></div></header>

      <section className="about-hero section section-dark"><div className="container about-hero-inner"><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to home</Link><p className="eyebrow amber">MFY / ABOUT US</p><h1>Engineering with<br /><span>intent.</span></h1><p>MFY Consulting Ltd supports Nigeria and West Africa&apos;s industrial growth through practical engineering expertise, procurement discipline and reliable field delivery.</p></div></section>

      <section className="section about-story"><div className="container about-story-grid"><div><p className="eyebrow">01 / WHO WE ARE</p><h2>Technical depth.<br /><span>Local understanding.</span></h2></div><div className="about-copy"><p className="about-lead">MFY Consulting Ltd is a fully integrated Engineering, Procurement, Manpower Supply and Petroleum Product Marketing organization.</p><p>Our track record spans petroleum product importation and distribution, construction and engineering project delivery. We add value to the oil and gas industry by connecting sound technical judgment with dependable procurement and execution.</p><p>We are working toward ISO 9001 certification and have built a reliable reputation in Nigeria&apos;s energy market. Our operations continue to diversify across engineering, refining, petroleum product distribution and marketing, plus machinery and spare-parts procurement with installation and commissioning.</p><p>Active onshore and offshore in Nigeria, we remain open to strategic alliances with engineering companies for specialist and project-specific delivery.</p></div></div></section>

      <section className="section section-dark about-capabilities"><div className="container about-cap-grid"><div><p className="eyebrow amber">02 / OUR DIRECTION</p><h2>Built for the<br /><span>work ahead.</span></h2><p className="about-muted">Our purpose is to help build the technical capacity and industrial infrastructure that keeps Nigeria and West Africa moving forward.</p></div><div className="capability-list"><div><span>01</span><b>Engineering & design</b><ArrowUpRight size={16} /></div><div><span>02</span><b>Procurement & supply</b><ArrowUpRight size={16} /></div><div><span>03</span><b>Construction & delivery</b><ArrowUpRight size={16} /></div><div><span>04</span><b>Petroleum products</b><ArrowUpRight size={16} /></div></div></div></section>

      <section className="section principles"><div className="container principles-grid"><div><p className="eyebrow">03 / OUR PRINCIPLES</p><h2>Standards that<br /><span>stay with us.</span></h2></div><div className="principle-items"><article><Compass size={25} /><h3>Practical expertise</h3><p>We turn technical requirements into solutions that can be built, operated and maintained in the real world.</p></article><article><ShieldCheck size={25} /><h3>Safety by design</h3><p>HSE is embedded in our planning, engineering, site execution and decision-making.</p></article><article><CheckCircle2 size={25} /><h3>Accountable delivery</h3><p>Clear ownership, transparent communication and disciplined controls keep every interface moving.</p></article></div></div></section>

      <section className="contact"><div className="container contact-inner"><p className="eyebrow amber">04 / LET&apos;S TALK</p><h2>Have a project<br /><em>in mind?</em></h2><p>Tell us where you are going. We will help you map the way there.</p><a className="button button-amber" href="mailto:Consultingmfy@gmail.com">Consultingmfy@gmail.com <ArrowUpRight size={17} /></a></div></section>
      <footer className="footer"><div className="container footer-grid"><div><Link className="brand brand-footer" href="/"><img className="brand-logo" src="/mfy-logo-transparent.png" alt="MFY logo" /><span className="brand-name">MFY Consulting Ltd</span></Link><p className="footer-tag">Integrated oil & gas<br />engineering services.</p></div><div><p className="footer-label">CONTACT</p><a href="mailto:Consultingmfy@gmail.com"><Mail size={14} /> Consultingmfy@gmail.com</a><a href="tel:+2348033779392"><Phone size={14} /> 08033779392</a><a href="tel:+2349077779746"><Phone size={14} /> 09077779746</a></div><div><p className="footer-label">OFFICE</p><p><MapPin size={14} /> B002 Kado Mall,<br />Ahmadu Bello Way, Abuja</p></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MFY Consulting Ltd. All rights reserved.</span><span>ENGINEERING WITH INTENT</span></div></footer>
    </main>
  )
}

/* eslint-disable react/no-unescaped-entities */
