'use client'

import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Menu, X, ShieldCheck, Compass, Cog, Truck, HardHat, Wrench, CheckCircle2, MapPin, Mail, Phone } from 'lucide-react'

const services = [
  { icon: Compass, index: '01', title: 'Engineering & Design', copy: 'Front-end engineering, detailed design and technical studies for safe, efficient facilities.', items: ['Conceptual & FEED studies', 'Process, mechanical & civil design', 'Piping, electrical & instrumentation', 'Brownfield modification design'] },
  { icon: Cog, index: '02', title: 'Project Management', copy: 'Disciplined project controls that keep complex work aligned from definition through delivery.', items: ['Project planning & controls', 'Cost, schedule & risk management', 'Contract administration', 'Interface & stakeholder management'] },
  { icon: Truck, index: '03', title: 'Procurement & Supply', copy: 'Reliable sourcing and expediting of critical equipment, materials and specialist services.', items: ['Equipment & materials sourcing', 'Vendor prequalification', 'Inspection & expediting', 'Logistics & inventory coordination'] },
  { icon: HardHat, index: '04', title: 'Construction & Installation', copy: 'Site-ready execution with a focus on constructability, quality and operational continuity.', items: ['Civil, structural & mechanical works', 'Piping fabrication & installation', 'Electrical & instrumentation', 'Site supervision & QA/QC'] },
  { icon: Wrench, index: '05', title: 'Commissioning & Maintenance', copy: 'Structured handover and lifecycle support that protects asset performance long after start-up.', items: ['Pre-commissioning & commissioning', 'Start-up assistance', 'Turnaround & shutdown support', 'Preventive maintenance programs'] },
  { icon: ShieldCheck, index: '06', title: 'HSE & Technical Support', copy: 'The systems, people and technical assurance required to operate safely and responsibly.', items: ['HSE management systems', 'Technical manpower supply', 'Inspection & integrity support', 'Training & competency development'] },
]

const navItems = [['Capabilities', '/capabilities'], ['Approach', '#approach'], ['Sectors', '#sectors'], ['About MFY', '/about']]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return (
    <main className="site-shell">
      <div className="utility"><div className="container utility-inner"><span>INTEGRATED ENGINEERING SERVICES</span><span className="utility-right"><MapPin size={13} /> Abuja, Nigeria <span className="utility-dot" /> <a href="mailto:Consultingmfy@gmail.com">Consultingmfy@gmail.com</a></span></div></div>
      <header className="site-header"><div className="container nav-inner"><a className="brand" href="#top" aria-label="MFY Consulting Ltd home"><img className="brand-logo" src="/mfy-logo-transparent.png" alt="MFY logo" /><span className="brand-name">MFY Consulting Ltd</span></a><nav className="desktop-nav" aria-label="Main navigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}<a className="nav-cta" href="#contact">Start a conversation <ArrowUpRight size={15} /></a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<a href="#contact" onClick={() => setMenuOpen(false)}>Start a conversation <ArrowUpRight size={15} /></a></nav>}</header>

      <section id="top" className="hero"><div className="hero-image" /><div className="hero-grid" /><div className="container hero-content"><p className="eyebrow amber">MFY / 01 — ENGINEERING WITH INTENT</p><h1>Engineering the<br /><em>energy</em> that moves<br />Nigeria forward.</h1><p className="hero-copy">Integrated oil & gas engineering services for operators, developers and partners who demand precision from concept to completion.</p><a className="button button-amber" href="#capabilities">Explore our capabilities <ArrowUpRight size={17} /></a></div><div className="hero-meta container"><span>06°27′N 03°23′E</span><span>OPERATING ACROSS WEST AFRICA</span></div></section>

      <section className="intro section"><div className="container intro-grid"><div><p className="eyebrow">01 / WHO WE ARE</p><h2>Technical depth.<br /><span>Local understanding.</span></h2></div><div className="intro-copy"><p>MFY Consulting Ltd is an integrated oil & gas engineering services company based in Abuja, Nigeria. We bring together the engineering expertise, project discipline and field capability required to deliver critical energy infrastructure.</p><p>From early-stage design to construction, commissioning and maintenance, our work is grounded in a clear understanding of the environments in which our clients operate.</p></div></div></section>

      <section id="capabilities" className="capabilities section section-dark"><div className="container"><div className="section-heading"><div><p className="eyebrow amber">02 / OUR CAPABILITIES</p><h2>One partner.<br /><span>Every phase.</span></h2></div><p>Integrated capability means fewer interfaces, clearer accountability and a more reliable path from ambition to asset.</p></div><div className="services-grid">{services.map(({ icon: Icon, index, title, copy, items }) => <article className="service-card" key={title}><div className="service-top"><span className="service-index">{index}</span><Icon size={24} strokeWidth={1.4} /></div><h3>{title}</h3><p>{copy}</p><ul>{items.map(item => <li key={item}><CheckCircle2 size={14} />{item}</li>)}</ul></article>)}</div></div></section>

      <section id="approach" className="approach section"><div className="container"><div className="approach-head"><p className="eyebrow">03 / HOW WE DELIVER</p><h2>Built for the real<br /><span>conditions of work.</span></h2></div><div className="process"><div className="process-line" />{[['01', 'Define', 'We align scope, risk and success criteria before a spade enters the ground.'], ['02', 'Engineer', 'We translate requirements into practical, buildable and compliant solutions.'], ['03', 'Execute', 'We coordinate people, materials and information with disciplined field control.'], ['04', 'Sustain', 'We hand over with confidence and remain present for the asset lifecycle.']].map(([n, title, copy]) => <div className="process-step" key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>

      <section id="sectors" className="sectors section"><div className="container sectors-grid"><div><p className="eyebrow">04 / OPERATING CONTEXT</p><h2>Experience that<br /><span>understands the terrain.</span></h2><p className="sector-intro">Our teams support energy projects across the environments and operating models that define West Africa’s oil & gas landscape.</p></div><div className="sector-list"><div><b>UPSTREAM</b><span>Onshore & offshore assets<br />Wellsite and production facilities</span></div><div><b>MIDSTREAM</b><span>Gathering systems & flowlines<br />Terminals, storage & logistics</span></div><div><b>DOWNSTREAM</b><span>Refining & petrochemical<br />Industrial utilities & infrastructure</span></div><div><b>PUBLIC & INDUSTRIAL</b><span>Power, water & critical infrastructure<br />Government and institutional projects</span></div></div></div></section>

      <section id="about" className="about section section-dark"><div className="container about-grid"><div><p className="eyebrow amber">05 / ABOUT MFY</p><h2>Local presence.<br /><span>International standard.</span></h2></div><div><p className="about-lead">We are building a Nigerian engineering company with the standards, systems and ambition to deliver work that stands alongside the best in the industry.</p><p>Our people combine regional knowledge with globally recognised engineering and project management practices. That means we understand the practical realities on the ground — and we have the technical rigour to navigate them.</p><div className="about-signature"><span>MFY CONSULTING LTD</span><small>Abuja · Nigeria</small></div><a className="button button-amber about-read-more" href="/about">Read Full About Us <ArrowUpRight size={17} /></a></div></div></section>

      <section className="assurance section"><div className="container assurance-grid"><div><p className="eyebrow">06 / OUR COMMITMENT</p><h2>Safe work is<br /><span>good business.</span></h2></div><div className="assurance-items"><div><ShieldCheck size={28} /><h3>Health, Safety & Environment</h3><p>We put the wellbeing of our people, communities and environment at the centre of every decision.</p></div><div><CheckCircle2 size={28} /><h3>Quality without compromise</h3><p>Clear standards, accountable systems and a culture of continuous improvement underpin our delivery.</p></div></div></div></section>

      <section id="contact" className="contact"><div className="container contact-inner"><p className="eyebrow amber">07 / LET&apos;S TALK</p><h2>Have a project<br /><em>in mind?</em></h2><p>Tell us where you are going. We will help you map the way there.</p><a className="button button-amber" href="mailto:Consultingmfy@gmail.com">Contact our team <ArrowUpRight size={17} /></a></div><div className="contact-corner">MFY / CONSULTING LTD<br />ENGINEERING WITH INTENT</div></section>

      <footer className="footer"><div className="container footer-grid"><div><a className="brand brand-footer" href="#top"><img className="brand-logo" src="/mfy-logo-transparent.png" alt="MFY logo" /><span className="brand-name">MFY Consulting Ltd</span></a><p className="footer-tag">Integrated oil & gas<br />engineering services.</p></div><div><p className="footer-label">CONTACT</p><a href="mailto:Consultingmfy@gmail.com"><Mail size={14} /> Consultingmfy@gmail.com</a><a href="tel:+2348033779392"><Phone size={14} /> 08033779392</a><a href="tel:+2349077779746"><Phone size={14} /> 09077779746</a></div><div><p className="footer-label">OFFICE</p><p><MapPin size={14} /> B002 Kado Mall,<br />Ahmadu Bello Way, Abuja</p></div><div><p className="footer-label">NAVIGATE</p><a href="#capabilities">Capabilities</a><a href="#about">About MFY</a><a href="#contact">Contact</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MFY Consulting Ltd. All rights reserved.</span><span>ENGINEERING WITH INTENT</span></div></footer>
    </main>
  )
}

// End of page

/* eslint-disable react/no-unescaped-entities */

